package com.insurance.business.model;

import com.springboot.simple.jdbc.model.BaseModel;

import java.util.Date;

public class CustomerModel extends BaseModel {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_customer.id
     *
     * @mbggenerated Mon Feb 08 10:39:56 CST 2021
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_customer.create_time
     *
     * @mbggenerated Mon Feb 08 10:39:56 CST 2021
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_customer.modified_time
     *
     * @mbggenerated Mon Feb 08 10:39:56 CST 2021
     */
    private Date modifiedTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_customer.deleted
     *
     * @mbggenerated Mon Feb 08 10:39:56 CST 2021
     */
    private Boolean deleted;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_customer.access_key
     *
     * @mbggenerated Mon Feb 08 10:39:56 CST 2021
     */
    private Long accessKey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_customer.customer_name
     *
     * @mbggenerated Mon Feb 08 10:39:56 CST 2021
     */
    private String customerName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_customer.login_name
     *
     * @mbggenerated Mon Feb 08 10:39:56 CST 2021
     */
    private String loginName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_customer.password
     *
     * @mbggenerated Mon Feb 08 10:39:56 CST 2021
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_customer.phone
     *
     * @mbggenerated Mon Feb 08 10:39:56 CST 2021
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_customer.certification
     *
     * @mbggenerated Mon Feb 08 10:39:56 CST 2021
     */
    private Boolean certification;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_customer.certification_time
     *
     * @mbggenerated Mon Feb 08 10:39:56 CST 2021
     */
    private Date certificationTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_customer.id
     *
     * @return the value of t_customer.id
     *
     * @mbggenerated Mon Feb 08 10:39:56 CST 2021
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_customer.id
     *
     * @param id the value for t_customer.id
     *
     * @mbggenerated Mon Feb 08 10:39:56 CST 2021
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_customer.create_time
     *
     * @return the value of t_customer.create_time
     *
     * @mbggenerated Mon Feb 08 10:39:56 CST 2021
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_customer.create_time
     *
     * @param createTime the value for t_customer.create_time
     *
     * @mbggenerated Mon Feb 08 10:39:56 CST 2021
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_customer.modified_time
     *
     * @return the value of t_customer.modified_time
     *
     * @mbggenerated Mon Feb 08 10:39:56 CST 2021
     */
    public Date getModifiedTime() {
        return modifiedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_customer.modified_time
     *
     * @param modifiedTime the value for t_customer.modified_time
     *
     * @mbggenerated Mon Feb 08 10:39:56 CST 2021
     */
    public void setModifiedTime(Date modifiedTime) {
        this.modifiedTime = modifiedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_customer.deleted
     *
     * @return the value of t_customer.deleted
     *
     * @mbggenerated Mon Feb 08 10:39:56 CST 2021
     */
    public Boolean getDeleted() {
        return deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_customer.deleted
     *
     * @param deleted the value for t_customer.deleted
     *
     * @mbggenerated Mon Feb 08 10:39:56 CST 2021
     */
    public void setDeleted(Boolean deleted) {
        this.deleted = deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_customer.access_key
     *
     * @return the value of t_customer.access_key
     *
     * @mbggenerated Mon Feb 08 10:39:56 CST 2021
     */
    public Long getAccessKey() {
        return accessKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_customer.access_key
     *
     * @param accessKey the value for t_customer.access_key
     *
     * @mbggenerated Mon Feb 08 10:39:56 CST 2021
     */
    public void setAccessKey(Long accessKey) {
        this.accessKey = accessKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_customer.customer_name
     *
     * @return the value of t_customer.customer_name
     *
     * @mbggenerated Mon Feb 08 10:39:56 CST 2021
     */
    public String getCustomerName() {
        return customerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_customer.customer_name
     *
     * @param customerName the value for t_customer.customer_name
     *
     * @mbggenerated Mon Feb 08 10:39:56 CST 2021
     */
    public void setCustomerName(String customerName) {
        this.customerName = customerName == null ? null : customerName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_customer.login_name
     *
     * @return the value of t_customer.login_name
     *
     * @mbggenerated Mon Feb 08 10:39:56 CST 2021
     */
    public String getLoginName() {
        return loginName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_customer.login_name
     *
     * @param loginName the value for t_customer.login_name
     *
     * @mbggenerated Mon Feb 08 10:39:56 CST 2021
     */
    public void setLoginName(String loginName) {
        this.loginName = loginName == null ? null : loginName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_customer.password
     *
     * @return the value of t_customer.password
     *
     * @mbggenerated Mon Feb 08 10:39:56 CST 2021
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_customer.password
     *
     * @param password the value for t_customer.password
     *
     * @mbggenerated Mon Feb 08 10:39:56 CST 2021
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_customer.phone
     *
     * @return the value of t_customer.phone
     *
     * @mbggenerated Mon Feb 08 10:39:56 CST 2021
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_customer.phone
     *
     * @param phone the value for t_customer.phone
     *
     * @mbggenerated Mon Feb 08 10:39:56 CST 2021
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_customer.certification
     *
     * @return the value of t_customer.certification
     *
     * @mbggenerated Mon Feb 08 10:39:56 CST 2021
     */
    public Boolean getCertification() {
        return certification;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_customer.certification
     *
     * @param certification the value for t_customer.certification
     *
     * @mbggenerated Mon Feb 08 10:39:56 CST 2021
     */
    public void setCertification(Boolean certification) {
        this.certification = certification;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_customer.certification_time
     *
     * @return the value of t_customer.certification_time
     *
     * @mbggenerated Mon Feb 08 10:39:56 CST 2021
     */
    public Date getCertificationTime() {
        return certificationTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_customer.certification_time
     *
     * @param certificationTime the value for t_customer.certification_time
     *
     * @mbggenerated Mon Feb 08 10:39:56 CST 2021
     */
    public void setCertificationTime(Date certificationTime) {
        this.certificationTime = certificationTime;
    }
}