package com.insurance.business.model;

import com.springboot.simple.jdbc.model.BaseModel;

import java.util.Date;

public class CustomerCertificationInfoModel extends BaseModel {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_customer_certification_info.id
     *
     * @mbggenerated Mon Feb 08 10:39:56 CST 2021
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_customer_certification_info.create_time
     *
     * @mbggenerated Mon Feb 08 10:39:56 CST 2021
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_customer_certification_info.modified_time
     *
     * @mbggenerated Mon Feb 08 10:39:56 CST 2021
     */
    private Date modifiedTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_customer_certification_info.deleted
     *
     * @mbggenerated Mon Feb 08 10:39:56 CST 2021
     */
    private Boolean deleted;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_customer_certification_info.access_key
     *
     * @mbggenerated Mon Feb 08 10:39:56 CST 2021
     */
    private Long accessKey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_customer_certification_info.customer_id
     *
     * @mbggenerated Mon Feb 08 10:39:56 CST 2021
     */
    private Long customerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_customer_certification_info.name
     *
     * @mbggenerated Mon Feb 08 10:39:56 CST 2021
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_customer_certification_info.birthday
     *
     * @mbggenerated Mon Feb 08 10:39:56 CST 2021
     */
    private Date birthday;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_customer_certification_info.identity_number
     *
     * @mbggenerated Mon Feb 08 10:39:56 CST 2021
     */
    private String identityNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_customer_certification_info.identity_positive
     *
     * @mbggenerated Mon Feb 08 10:39:56 CST 2021
     */
    private String identityPositive;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_customer_certification_info.identity_reverse
     *
     * @mbggenerated Mon Feb 08 10:39:56 CST 2021
     */
    private String identityReverse;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_customer_certification_info.take_identity_image
     *
     * @mbggenerated Mon Feb 08 10:39:56 CST 2021
     */
    private String takeIdentityImage;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_customer_certification_info.id
     *
     * @return the value of t_customer_certification_info.id
     *
     * @mbggenerated Mon Feb 08 10:39:56 CST 2021
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_customer_certification_info.id
     *
     * @param id the value for t_customer_certification_info.id
     *
     * @mbggenerated Mon Feb 08 10:39:56 CST 2021
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_customer_certification_info.create_time
     *
     * @return the value of t_customer_certification_info.create_time
     *
     * @mbggenerated Mon Feb 08 10:39:56 CST 2021
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_customer_certification_info.create_time
     *
     * @param createTime the value for t_customer_certification_info.create_time
     *
     * @mbggenerated Mon Feb 08 10:39:56 CST 2021
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_customer_certification_info.modified_time
     *
     * @return the value of t_customer_certification_info.modified_time
     *
     * @mbggenerated Mon Feb 08 10:39:56 CST 2021
     */
    public Date getModifiedTime() {
        return modifiedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_customer_certification_info.modified_time
     *
     * @param modifiedTime the value for t_customer_certification_info.modified_time
     *
     * @mbggenerated Mon Feb 08 10:39:56 CST 2021
     */
    public void setModifiedTime(Date modifiedTime) {
        this.modifiedTime = modifiedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_customer_certification_info.deleted
     *
     * @return the value of t_customer_certification_info.deleted
     *
     * @mbggenerated Mon Feb 08 10:39:56 CST 2021
     */
    public Boolean getDeleted() {
        return deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_customer_certification_info.deleted
     *
     * @param deleted the value for t_customer_certification_info.deleted
     *
     * @mbggenerated Mon Feb 08 10:39:56 CST 2021
     */
    public void setDeleted(Boolean deleted) {
        this.deleted = deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_customer_certification_info.access_key
     *
     * @return the value of t_customer_certification_info.access_key
     *
     * @mbggenerated Mon Feb 08 10:39:56 CST 2021
     */
    public Long getAccessKey() {
        return accessKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_customer_certification_info.access_key
     *
     * @param accessKey the value for t_customer_certification_info.access_key
     *
     * @mbggenerated Mon Feb 08 10:39:56 CST 2021
     */
    public void setAccessKey(Long accessKey) {
        this.accessKey = accessKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_customer_certification_info.customer_id
     *
     * @return the value of t_customer_certification_info.customer_id
     *
     * @mbggenerated Mon Feb 08 10:39:56 CST 2021
     */
    public Long getCustomerId() {
        return customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_customer_certification_info.customer_id
     *
     * @param customerId the value for t_customer_certification_info.customer_id
     *
     * @mbggenerated Mon Feb 08 10:39:56 CST 2021
     */
    public void setCustomerId(Long customerId) {
        this.customerId = customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_customer_certification_info.name
     *
     * @return the value of t_customer_certification_info.name
     *
     * @mbggenerated Mon Feb 08 10:39:56 CST 2021
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_customer_certification_info.name
     *
     * @param name the value for t_customer_certification_info.name
     *
     * @mbggenerated Mon Feb 08 10:39:56 CST 2021
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_customer_certification_info.birthday
     *
     * @return the value of t_customer_certification_info.birthday
     *
     * @mbggenerated Mon Feb 08 10:39:56 CST 2021
     */
    public Date getBirthday() {
        return birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_customer_certification_info.birthday
     *
     * @param birthday the value for t_customer_certification_info.birthday
     *
     * @mbggenerated Mon Feb 08 10:39:56 CST 2021
     */
    public void setBirthday(Date birthday) {
        this.birthday = birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_customer_certification_info.identity_number
     *
     * @return the value of t_customer_certification_info.identity_number
     *
     * @mbggenerated Mon Feb 08 10:39:56 CST 2021
     */
    public String getIdentityNumber() {
        return identityNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_customer_certification_info.identity_number
     *
     * @param identityNumber the value for t_customer_certification_info.identity_number
     *
     * @mbggenerated Mon Feb 08 10:39:56 CST 2021
     */
    public void setIdentityNumber(String identityNumber) {
        this.identityNumber = identityNumber == null ? null : identityNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_customer_certification_info.identity_positive
     *
     * @return the value of t_customer_certification_info.identity_positive
     *
     * @mbggenerated Mon Feb 08 10:39:56 CST 2021
     */
    public String getIdentityPositive() {
        return identityPositive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_customer_certification_info.identity_positive
     *
     * @param identityPositive the value for t_customer_certification_info.identity_positive
     *
     * @mbggenerated Mon Feb 08 10:39:56 CST 2021
     */
    public void setIdentityPositive(String identityPositive) {
        this.identityPositive = identityPositive == null ? null : identityPositive.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_customer_certification_info.identity_reverse
     *
     * @return the value of t_customer_certification_info.identity_reverse
     *
     * @mbggenerated Mon Feb 08 10:39:56 CST 2021
     */
    public String getIdentityReverse() {
        return identityReverse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_customer_certification_info.identity_reverse
     *
     * @param identityReverse the value for t_customer_certification_info.identity_reverse
     *
     * @mbggenerated Mon Feb 08 10:39:56 CST 2021
     */
    public void setIdentityReverse(String identityReverse) {
        this.identityReverse = identityReverse == null ? null : identityReverse.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_customer_certification_info.take_identity_image
     *
     * @return the value of t_customer_certification_info.take_identity_image
     *
     * @mbggenerated Mon Feb 08 10:39:56 CST 2021
     */
    public String getTakeIdentityImage() {
        return takeIdentityImage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_customer_certification_info.take_identity_image
     *
     * @param takeIdentityImage the value for t_customer_certification_info.take_identity_image
     *
     * @mbggenerated Mon Feb 08 10:39:56 CST 2021
     */
    public void setTakeIdentityImage(String takeIdentityImage) {
        this.takeIdentityImage = takeIdentityImage == null ? null : takeIdentityImage.trim();
    }
}