package com.insurance.business.model;

import com.springboot.simple.jdbc.model.BaseModel;

import java.util.Date;

public class PolicyModel extends BaseModel {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_policy.id
     *
     * @mbggenerated Sun Mar 21 12:17:44 CST 2021
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_policy.create_time
     *
     * @mbggenerated Sun Mar 21 12:17:44 CST 2021
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_policy.modified_time
     *
     * @mbggenerated Sun Mar 21 12:17:44 CST 2021
     */
    private Date modifiedTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_policy.deleted
     *
     * @mbggenerated Sun Mar 21 12:17:44 CST 2021
     */
    private Boolean deleted;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_policy.access_key
     *
     * @mbggenerated Sun Mar 21 12:17:44 CST 2021
     */
    private Long accessKey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_policy.policy_name
     *
     * @mbggenerated Sun Mar 21 12:17:44 CST 2021
     */
    private String policyName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_policy.insure_user_id
     *
     * @mbggenerated Sun Mar 21 12:17:44 CST 2021
     */
    private Long insureUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_policy.benefit_user_id
     *
     * @mbggenerated Sun Mar 21 12:17:44 CST 2021
     */
    private Long benefitUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_policy.insurance_id
     *
     * @mbggenerated Sun Mar 21 12:17:44 CST 2021
     */
    private Long insuranceId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_policy.duration
     *
     * @mbggenerated Sun Mar 21 12:17:44 CST 2021
     */
    private Integer duration;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_policy.file_path
     *
     * @mbggenerated Sun Mar 21 12:17:44 CST 2021
     */
    private String filePath;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_policy.id
     *
     * @return the value of t_policy.id
     *
     * @mbggenerated Sun Mar 21 12:17:44 CST 2021
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_policy.id
     *
     * @param id the value for t_policy.id
     *
     * @mbggenerated Sun Mar 21 12:17:44 CST 2021
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_policy.create_time
     *
     * @return the value of t_policy.create_time
     *
     * @mbggenerated Sun Mar 21 12:17:44 CST 2021
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_policy.create_time
     *
     * @param createTime the value for t_policy.create_time
     *
     * @mbggenerated Sun Mar 21 12:17:44 CST 2021
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_policy.modified_time
     *
     * @return the value of t_policy.modified_time
     *
     * @mbggenerated Sun Mar 21 12:17:44 CST 2021
     */
    public Date getModifiedTime() {
        return modifiedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_policy.modified_time
     *
     * @param modifiedTime the value for t_policy.modified_time
     *
     * @mbggenerated Sun Mar 21 12:17:44 CST 2021
     */
    public void setModifiedTime(Date modifiedTime) {
        this.modifiedTime = modifiedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_policy.deleted
     *
     * @return the value of t_policy.deleted
     *
     * @mbggenerated Sun Mar 21 12:17:44 CST 2021
     */
    public Boolean getDeleted() {
        return deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_policy.deleted
     *
     * @param deleted the value for t_policy.deleted
     *
     * @mbggenerated Sun Mar 21 12:17:44 CST 2021
     */
    public void setDeleted(Boolean deleted) {
        this.deleted = deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_policy.access_key
     *
     * @return the value of t_policy.access_key
     *
     * @mbggenerated Sun Mar 21 12:17:44 CST 2021
     */
    public Long getAccessKey() {
        return accessKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_policy.access_key
     *
     * @param accessKey the value for t_policy.access_key
     *
     * @mbggenerated Sun Mar 21 12:17:44 CST 2021
     */
    public void setAccessKey(Long accessKey) {
        this.accessKey = accessKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_policy.policy_name
     *
     * @return the value of t_policy.policy_name
     *
     * @mbggenerated Sun Mar 21 12:17:44 CST 2021
     */
    public String getPolicyName() {
        return policyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_policy.policy_name
     *
     * @param policyName the value for t_policy.policy_name
     *
     * @mbggenerated Sun Mar 21 12:17:44 CST 2021
     */
    public void setPolicyName(String policyName) {
        this.policyName = policyName == null ? null : policyName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_policy.insure_user_id
     *
     * @return the value of t_policy.insure_user_id
     *
     * @mbggenerated Sun Mar 21 12:17:44 CST 2021
     */
    public Long getInsureUserId() {
        return insureUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_policy.insure_user_id
     *
     * @param insureUserId the value for t_policy.insure_user_id
     *
     * @mbggenerated Sun Mar 21 12:17:44 CST 2021
     */
    public void setInsureUserId(Long insureUserId) {
        this.insureUserId = insureUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_policy.benefit_user_id
     *
     * @return the value of t_policy.benefit_user_id
     *
     * @mbggenerated Sun Mar 21 12:17:44 CST 2021
     */
    public Long getBenefitUserId() {
        return benefitUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_policy.benefit_user_id
     *
     * @param benefitUserId the value for t_policy.benefit_user_id
     *
     * @mbggenerated Sun Mar 21 12:17:44 CST 2021
     */
    public void setBenefitUserId(Long benefitUserId) {
        this.benefitUserId = benefitUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_policy.insurance_id
     *
     * @return the value of t_policy.insurance_id
     *
     * @mbggenerated Sun Mar 21 12:17:44 CST 2021
     */
    public Long getInsuranceId() {
        return insuranceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_policy.insurance_id
     *
     * @param insuranceId the value for t_policy.insurance_id
     *
     * @mbggenerated Sun Mar 21 12:17:44 CST 2021
     */
    public void setInsuranceId(Long insuranceId) {
        this.insuranceId = insuranceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_policy.duration
     *
     * @return the value of t_policy.duration
     *
     * @mbggenerated Sun Mar 21 12:17:44 CST 2021
     */
    public Integer getDuration() {
        return duration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_policy.duration
     *
     * @param duration the value for t_policy.duration
     *
     * @mbggenerated Sun Mar 21 12:17:44 CST 2021
     */
    public void setDuration(Integer duration) {
        this.duration = duration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_policy.file_path
     *
     * @return the value of t_policy.file_path
     *
     * @mbggenerated Sun Mar 21 12:17:44 CST 2021
     */
    public String getFilePath() {
        return filePath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_policy.file_path
     *
     * @param filePath the value for t_policy.file_path
     *
     * @mbggenerated Sun Mar 21 12:17:44 CST 2021
     */
    public void setFilePath(String filePath) {
        this.filePath = filePath == null ? null : filePath.trim();
    }
}